version: '3.8'

services:
  selfservice-celero:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selfservice-celero-app
    restart: always
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    volumes:
      # Logs de nginx
      - ./logs/nginx:/var/log/nginx
      # Certificados SSL
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    labels:
      - "com.celero.service=selfservice"
      - "com.celero.description=Self Service Portal Celero"
      - "com.celero.environment=production"

  # Nginx como proxy reverso con SSL
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: selfservice-celero-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./deploy/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - selfservice-celero
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot para certificados SSL Let's Encrypt
  certbot:
    image: certbot/certbot
    container_name: selfservice-celero-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge

volumes:
  nginx-logs:
  certbot-conf:
  certbot-www: